### ISSUE TITLE
Error in RPT logs

### ISSUE THREAD

**Issue by DEH4NK** [nk3nny/LambsDanger#155]
**Mods (complete and add to the following information):**

- **Arma 3:** Version: 1.98.146373
- **CBA:** Version: 3.15.1
- **LAMBS_DANGER:** Version: 2.4.4

**Description:**

Errors in the server RPT

**Steps to reproduce:**
 ...

**Expected behavior:**

 ...

**Where did the issue occur?**

Self-Hosted Multiplayer

**Additional context:**

11:52:25 Error in expression <dex, _sound];
11:52:25 Error position: <lambs_danger_CalloutCacheNamespace setVa>
11:52:25 Error Undefined variable in expression: lambs_danger_calloutcachenamespace
11:52:25 File z\lambs\addons\danger\functions\fnc_doCallout.sqf..., line 88
11:52:25 Error in expression <ior, _callout];
11:52:25 Error position: <lambs_danger_CalloutCacheNamespace getVa>
11:52:25 Error Undefined variable in expression: lambs_danger_calloutcachenamespace
11:52:25 File z\lambs\addons\danger\functions\fnc_doCallout.sqf..., line 38

**Log Files:**
([pastebin](https://pastebin.com/3TNYPvLY))

**Screenshots:**
 ...

**Comment by diwako** [comment]
Hey thanks for the report.

We already looked through the RPT. Needed mods are installed so the our mod should work. However these errors are a bit strange, so we kind of want to dig deeper into the issue.

First we need to know if the file that should create the missing object is being run, to do this, you simply need to check a few variables on your server. You can do this with the CBA target debugging tool or otherwise. Just to make sure, we need to know the values that the SERVER has, not your clients.

Those are:

- lambs_danger
- lambs_danger_CalloutCacheNamespace
- lambs_danger_drawRectCacheGame
- lambs_danger_drawRectInUseGame
- lambs_danger_drawRectCacheEGSpectator
- lambs_danger_drawRectInUseEGSpectator
- lambs_danger_drawRectCacheCurator
- lambs_danger_drawRectInUseCurator


As an explanation. Most of the ones I just said are being defined around the same time as the one that is causing the issue, the variables with "draw" in their name are just there for debug reasons. Since you are not running debug on your server, all of them should be an empty array (`[]`).
So with this we can easily check if the file has been ran or not.

**Comment by DEH4NK** [comment]
Greetings, please give me an exact step-by-step instruction on what I should do, unfortunately I have a language barrier and Google translator cannot cope with this.

**Comment by diwako** [comment]
Execute this globally into your debug console while connected to your server. Then check the server's RPT file for the output.

```sqf
if !(isServer) exitWith {};
diag_log "=========LAMBS DEBUG BEGIN=========";
{
    diag_log format ["%1: %2", _x, missionNamespace getVariable [_x, "NOT_SET"]];
} forEach ["lambs_danger",
"lambs_danger_CalloutCacheNamespace",
"lambs_danger_drawRectCacheGame",
"lambs_danger_drawRectInUseGame",
"lambs_danger_drawRectCacheEGSpectator",
"lambs_danger_drawRectInUseEGSpectator",
"lambs_danger_drawRectCacheCurator",
"lambs_danger_drawRectInUseCurator"];
diag_log "=========LAMBS DEBUG END=========";
```

**Comment by DEH4NK** [comment]
it is not easy to do with the EXILE mod that I use, this is what he writes to me: Scripting function 'bis_fnc_debugconsoleexec' is not allowed to be remotely executed

**Comment by diwako** [comment]
By any chance do you have CBA target debugging enabled?
https://github.com/CBATeam/CBA_A3/wiki/Target-Debugging

It is the list on the very right of the screenshot in the URL link from above.

**Comment by DEH4NK** [comment]
I figured it out, a3_infiSTAR_Exile was blocking console commands. Here's the result:
23:49:32 "=========LAMBS DEBUG BEGIN========="
23:49:32 "lambs_danger: true"
23:49:32 "lambs_danger_CalloutCacheNamespace: NOT_SET"
23:49:32 "lambs_danger_drawRectCacheGame: NOT_SET"
23:49:32 "lambs_danger_drawRectInUseGame: NOT_SET"
23:49:32 "lambs_danger_drawRectCacheEGSpectator: NOT_SET"
23:49:32 "lambs_danger_drawRectInUseEGSpectator: NOT_SET"
23:49:32 "lambs_danger_drawRectCacheCurator: NOT_SET"
23:49:32 "lambs_danger_drawRectInUseCurator: NOT_SET"
23:49:32 "=========LAMBS DEBUG END========="

**Comment by diwako** [comment]
It appears, that the "post init" of the danger addon did not run AT ALL. This could be by another mod blocking this behavior.

It could be either Exile or infiSTAR.

It sadly is nothing we can fix on our side...

**Comment by DEH4NK** [comment]
Yes, most likely the problem in Exile is very deeply rewritten, in any case, the AI behavior has changed for the better, and apart from a few errors in the RPT, there are no problems on the server. Thanks again guys to you all for this mod !!!

**Comment by diwako** [comment]
@DEH4NK 

one suggestion to get rid if the error messages, you can simply disable the feature that is throwing this error.

Just set this CBA setting in your server CBA setting file or config.

`lambs_danger_disableAICallouts = false;`
