### ISSUE TITLE
[Feature request] AI hearing (suppressors and without)

### ISSUE THREAD

**Issue by tyl3r99** [nk3nny/LambsDanger#211]
**Describe your requested feature**

Would it be possible like vcom to have a cba setting to adjust ai hearing of unsuppressed gunfire and suppressed? 

We could fine tune them to our liking and could improve our stealth gameplay experiences. 

Thank you in advance.

**Comment by nk3nny** [comment]
https://youtu.be/-9IyRyIfumg

Short story: Depending on how the issue is approached, it is outside the scope of the mod. 

Longer story: Stealth and Arma is complex.  As I say in the video, Metal Gear Solid, Arma is not. For perfect stealth, what you'll want is to score headshots. Killing units instantly and outside the visual field of any allies. Were than easy fix, we'd look into it. But to make it fully compatible across all mods and all platforms-- that would require a massive amount of work. 

:) 

This issue will be closed after 24h
