### ISSUE TITLE
Add missing "type" entry to waypoints

### ISSUE THREAD

**Issue by EinfachJul** [nk3nny/LambsDanger#67]
**Is your enhancement related to a problem?**

It is to my knowledge currently not possible to spawn LAMBS Waypoints via script. Since I often spawn AI in my missions, that`s quite a bummer.

**Solution you'd like:**

Add a "type" entry for each waypoint, so it can be set by [setWaypointType](https://community.bistudio.com/wiki/setWaypointType)

**Comment by nk3nny** [comment]
We've had a brief look at this and we are not sure it is possible.  Or do you have an example otherwise? :) 

It is possible to run the script on spawned groups. After all the script only calls a function  Here are some examples: First argument is a group or unit. Secondary argument is optional and sets range in meters. 

[group1, 500] spawn lambs_wp_fnc_taskRush;
[group1, 700] spawn lambs_wp_fnc_taskCreep;
[group1, 300] spawn lambs_wp_fnc_taskHunt;
and so on. 

A known limitation is that units which are switched between headless clients will quit the active script. 

--- 
The waypoints themselves are actually also scriptswhich can be called in a similar manner. Just copy the script names from the appropriate WP. :)

**Comment by EinfachJul** [comment]
Thanks for the reply!

With the functions you provided making the change won't be necessary. Actually, I prefere it this way, scripting waypoints is quite a hassle.
Anyway, I'd recommend adding the functions some documentation, so it's easier to find for others.

**Comment by nk3nny** [comment]
Will do.
